# Generated by Django 6.1.1 on 2026-09-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promovido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_completa', models.TextField(blank=True, null=True)),
                ('seccion_electoral', models.IntegerField(blank=True, null=True)),
                ('distrito_zona', models.CharField(blank=True, max_length=100, null=True)),
                ('confirma_apoyo', models.CharField(default='No', max_length=2)),
                ('medio_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable_captura', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotacionAyuntamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.IntegerField(unique=True)),
                ('casillas', models.IntegerField()),
                ('lista_nominal', models.IntegerField()),
                ('num_votos_validos', models.IntegerField()),
                ('participacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pan', models.IntegerField(default=0)),
                ('pri', models.IntegerField(default=0)),
                ('prd', models.IntegerField(default=0)),
                ('pvem', models.IntegerField(default=0)),
                ('pt', models.IntegerField(default=0)),
                ('mc', models.IntegerField(default=0)),
                ('morena', models.IntegerField(default=0)),
                ('naem', models.IntegerField(default=0)),
                ('partido_ganador', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VotacionDiputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.IntegerField(unique=True)),
                ('casillas', models.IntegerField()),
                ('lista_nominal', models.IntegerField()),
                ('num_votos_validos', models.IntegerField()),
                ('participacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pan', models.IntegerField(default=0)),
                ('pri', models.IntegerField(default=0)),
                ('prd', models.IntegerField(default=0)),
                ('pvem', models.IntegerField(default=0)),
                ('pt', models.IntegerField(default=0)),
                ('mc', models.IntegerField(default=0)),
                ('morena', models.IntegerField(default=0)),
                ('naem', models.IntegerField(default=0)),
                ('partido_ganador', models.CharField(max_length=50)),
            ],
        ),
    ]
