# Generated by Django 6.1.1 on 2026-09-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('casa_encuestadora', models.CharField(blank=True, default='General', max_length=100)),
                ('pan', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pri', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('prd', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pvem', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pt', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mc', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('morena', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('naem', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('indecisos', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
